import { useState, useEffect, useCallback } from "react";

// ─── Utility ────────────────────────────────────────────────────────────────
const LS_KEY = "cricket_app_v1";
const save = (data) => localStorage.setItem(LS_KEY, JSON.stringify(data));
const load = () => { try { return JSON.parse(localStorage.getItem(LS_KEY)) || {}; } catch { return {}; } };

const rr = (runs, balls) => balls === 0 ? "0.00" : ((runs / balls) * 6).toFixed(2);
const overStr = (balls) => `${Math.floor(balls / 6)}.${balls % 6}`;
const nowDate = () => new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

// ─── PDF Generator ───────────────────────────────────────────────────────────
function generatePDF(match) {
  const { teamA, teamB, innings1, innings2, venue, motm, date, toss, overs } = match;
  const winner = (() => {
    if (!innings2 || !innings2.completed) return null;
    if (innings2.runs > innings1.runs) return `${teamB} won by ${innings2.wickets < 10 ? 10 - innings2.wickets : 0} wickets`;
    if (innings1.runs > innings2.runs) return `${teamA} won by ${innings1.runs - innings2.runs} runs`;
    return "Match Tied";
  })();

  const batTable = (inn, team) => {
    const rows = (inn.batsmen || []).map(b =>
      `<tr><td>${b.name}</td><td>${b.howOut || "not out"}</td><td>${b.runs}</td><td>${b.balls}</td><td>${b.fours}</td><td>${b.sixes}</td><td>${b.balls > 0 ? ((b.runs / b.balls) * 100).toFixed(1) : "0.0"}</td></tr>`
    ).join("");
    return `<h3 style="color:#f97316;margin:12px 0 4px">${team} Batting</h3>
    <table style="width:100%;border-collapse:collapse;font-size:11px">
      <thead><tr style="background:#1e293b;color:#94a3b8">${["Batsman","Dismissal","R","B","4s","6s","SR"].map(h=>`<th style="padding:4px 6px;text-align:left">${h}</th>`).join("")}</tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <p style="font-size:11px;margin:4px 0">Extras: ${inn.extras?.total || 0} (wd: ${inn.extras?.wides||0}, nb: ${inn.extras?.noballs||0})</p>
    <p style="font-size:13px;font-weight:bold;margin:4px 0">Total: ${inn.runs}/${inn.wickets} (${overStr(inn.balls)} ov)</p>`;
  };

  const bowlTable = (inn) => {
    const rows = (inn.bowlers || []).filter(b => b.balls > 0).map(b =>
      `<tr><td>${b.name}</td><td>${overStr(b.balls)}</td><td>${b.runs}</td><td>${b.wickets}</td><td>${b.balls > 0 ? ((b.runs / b.balls) * 6).toFixed(2) : "0.00"}</td></tr>`
    ).join("");
    return `<h3 style="color:#06b6d4;margin:12px 0 4px">Bowling</h3>
    <table style="width:100%;border-collapse:collapse;font-size:11px">
      <thead><tr style="background:#1e293b;color:#94a3b8">${["Bowler","O","R","W","Econ"].map(h=>`<th style="padding:4px 6px;text-align:left">${h}</th>`).join("")}</tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
  };

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
  <title>Scorecard - ${teamA} vs ${teamB}</title>
  <style>
    body{font-family:Georgia,serif;background:#0f172a;color:#e2e8f0;padding:24px;max-width:700px;margin:auto}
    table{width:100%;border-collapse:collapse} td,th{padding:4px 6px;border-bottom:1px solid #1e293b}
    tr:hover{background:#1e293b} h1{color:#f97316} h2{color:#94a3b8;border-bottom:1px solid #334155;padding-bottom:4px}
    .badge{display:inline-block;background:#f97316;color:#000;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:bold}
  </style></head><body>
  <h1>🏏 Cricket Scorecard</h1>
  <p><strong>Match:</strong> ${teamA} vs ${teamB} | <strong>Date:</strong> ${date || nowDate()} | <strong>Venue:</strong> ${venue || "Local Ground"}</p>
  <p><strong>Format:</strong> T${overs || 20} | <strong>Toss:</strong> ${toss || "—"}</p>
  ${winner ? `<p class="badge">${winner}</p>` : ""}
  ${motm ? `<p><strong>🏆 Man of the Match:</strong> ${motm}</p>` : ""}
  <h2>1st Innings — ${teamA}</h2>
  ${innings1 ? batTable(innings1, teamA) : "<p>No data</p>"}
  ${innings1 ? bowlTable(innings1) : ""}
  <h2>2nd Innings — ${teamB}</h2>
  ${innings2 ? batTable(innings2, teamB) : "<p>Not played</p>"}
  ${innings2 ? bowlTable(innings2) : ""}
  <p style="font-size:10px;color:#475569;margin-top:24px">Generated by Cricket Scorer App</p>
  </body></html>`;

  const w = window.open("", "_blank");
  w.document.write(html);
  w.document.close();
  setTimeout(() => w.print(), 400);
}

// ─── Screens ─────────────────────────────────────────────────────────────────
const SCREENS = { HOME: "home", SETUP: "setup", TOSS: "toss", TEAMS: "teams", SCORING: "scoring", INNINGS_BREAK: "innings_break", SUMMARY: "summary", HISTORY: "history" };

// ════════════════════════════════════════════════════════════════════════════
export default function App() {
  const [dark, setDark] = useState(true);
  const [screen, setScreen] = useState(SCREENS.HOME);
  const [match, setMatch] = useState(null);
  const [history, setHistory] = useState([]);
  const [toast, setToast] = useState(null);

  useEffect(() => {
    const d = load();
    if (d.history) setHistory(d.history);
    if (d.activeMatch) { setMatch(d.activeMatch); setScreen(SCREENS.SCORING); }
  }, []);

  const showToast = (msg, type = "success") => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 2500);
  };

  const saveMatch = useCallback((m) => {
    setMatch(m);
    const d = load();
    d.activeMatch = m;
    save(d);
  }, []);

  const finishMatch = useCallback((m) => {
    const d = load();
    const finished = { ...m, finishedAt: Date.now() };
    d.activeMatch = null;
    d.history = [finished, ...(d.history || []).slice(0, 19)];
    save(d);
    setHistory(d.history);
    setMatch(finished);
    setScreen(SCREENS.SUMMARY);
  }, []);

  const bg = dark ? "bg-[#080f1a]" : "bg-slate-100";
  const text = dark ? "text-slate-100" : "text-slate-900";

  return (
    <div className={`min-h-screen ${bg} ${text} transition-colors duration-300`} style={{ fontFamily: "'Segoe UI', system-ui, sans-serif" }}>
      {/* Toast */}
      {toast && (
        <div className={`fixed top-4 left-1/2 -translate-x-1/2 z-50 px-5 py-3 rounded-xl text-white font-semibold shadow-2xl transition-all duration-300 ${toast.type === "error" ? "bg-red-600" : "bg-emerald-600"}`}>
          {toast.msg}
        </div>
      )}

      {screen === SCREENS.HOME && <HomeScreen dark={dark} setDark={setDark} setScreen={setScreen} history={history} setMatch={setMatch} showToast={showToast} />}
      {screen === SCREENS.SETUP && <SetupScreen dark={dark} setScreen={setScreen} setMatch={saveMatch} showToast={showToast} />}
      {screen === SCREENS.TEAMS && <TeamsScreen dark={dark} match={match} setMatch={saveMatch} setScreen={setScreen} showToast={showToast} />}
      {screen === SCREENS.TOSS && <TossScreen dark={dark} match={match} setMatch={saveMatch} setScreen={setScreen} />}
      {screen === SCREENS.SCORING && match && <ScoringScreen dark={dark} match={match} setMatch={saveMatch} setScreen={setScreen} finishMatch={finishMatch} showToast={showToast} />}
      {screen === SCREENS.INNINGS_BREAK && match && <InningsBreak dark={dark} match={match} setMatch={saveMatch} setScreen={setScreen} showToast={showToast} />}
      {screen === SCREENS.SUMMARY && match && <SummaryScreen dark={dark} match={match} setScreen={setScreen} showToast={showToast} />}
      {screen === SCREENS.HISTORY && <HistoryScreen dark={dark} history={history} setScreen={setScreen} setMatch={setMatch} />}
    </div>
  );
}

// ─── HomeScreen ──────────────────────────────────────────────────────────────
function HomeScreen({ dark, setDark, setScreen, history, setMatch, showToast }) {
  const card = dark ? "bg-[#0d1929] border-[#1e3a5f]" : "bg-white border-slate-200";
  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-10">
      {/* Header */}
      <div className="w-full max-w-md flex justify-between items-center mb-8">
        <div>
          <h1 className="text-4xl font-black tracking-tight text-orange-400">🏏 CricScore</h1>
          <p className={`text-sm mt-1 ${dark ? "text-slate-400" : "text-slate-500"}`}>Local Match Scorer</p>
        </div>
        <button onClick={() => setDark(d => !d)} className={`w-10 h-10 rounded-full flex items-center justify-center border ${dark ? "border-slate-600 bg-slate-800 text-yellow-300" : "border-slate-300 bg-white text-slate-700"}`}>
          {dark ? "☀️" : "🌙"}
        </button>
      </div>

      {/* Hero */}
      <div className={`w-full max-w-md rounded-2xl border p-6 mb-6 ${card} shadow-2xl`}>
        <div className="text-center mb-6">
          <div className="text-6xl mb-2">🏆</div>
          <h2 className="text-2xl font-bold">Start Scoring</h2>
          <p className={`text-sm mt-1 ${dark ? "text-slate-400" : "text-slate-500"}`}>Ball-by-ball scoring for local cricket</p>
        </div>
        <button onClick={() => setScreen(SCREENS.SETUP)} className="w-full py-4 bg-orange-500 hover:bg-orange-400 text-black font-black text-xl rounded-2xl transition-all duration-200 active:scale-95 shadow-lg shadow-orange-500/30">
          🎯 New Match
        </button>
      </div>

      {/* Quick actions */}
      <div className="w-full max-w-md grid grid-cols-2 gap-3 mb-6">
        <button onClick={() => setScreen(SCREENS.HISTORY)} className={`py-4 rounded-2xl border font-bold flex flex-col items-center gap-1 ${card} hover:border-orange-500 transition-all`}>
          <span className="text-2xl">📋</span>
          <span className="text-sm">Match History</span>
          <span className={`text-xs ${dark ? "text-slate-400" : "text-slate-500"}`}>{history.length} matches</span>
        </button>
        <button onClick={() => {
          const d = JSON.parse(localStorage.getItem(LS_KEY) || "{}");
          if (d.activeMatch) { setMatch(d.activeMatch); setScreen(SCREENS.SCORING); }
          else { alert("No active match found."); }
        }} className={`py-4 rounded-2xl border font-bold flex flex-col items-center gap-1 ${card} hover:border-cyan-500 transition-all`}>
          <span className="text-2xl">▶️</span>
          <span className="text-sm">Resume Match</span>
          <span className={`text-xs ${dark ? "text-slate-400" : "text-slate-500"}`}>Continue scoring</span>
        </button>
      </div>

      {/* Recent */}
      {history.length > 0 && (
        <div className="w-full max-w-md">
          <h3 className={`text-sm font-semibold mb-2 ${dark ? "text-slate-400" : "text-slate-500"}`}>RECENT MATCHES</h3>
          <div className="space-y-2">
            {history.slice(0, 3).map((m, i) => (
              <div key={i} onClick={() => { setMatch(m); setScreen(SCREENS.SUMMARY); }} className={`p-3 rounded-xl border cursor-pointer ${card} hover:border-orange-500 transition-all`}>
                <div className="flex justify-between items-center">
                  <span className="font-semibold text-sm">{m.teamA} vs {m.teamB}</span>
                  <span className={`text-xs ${dark ? "text-slate-400" : "text-slate-500"}`}>{m.date || ""}</span>
                </div>
                <div className="flex gap-3 mt-1 text-xs text-orange-400">
                  <span>{m.innings1?.runs}/{m.innings1?.wickets} ({overStr(m.innings1?.balls || 0)})</span>
                  {m.innings2 && <span>| {m.innings2.runs}/{m.innings2.wickets} ({overStr(m.innings2.balls || 0)})</span>}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── SetupScreen ─────────────────────────────────────────────────────────────
function SetupScreen({ dark, setScreen, setMatch }) {
  const [teamA, setTeamA] = useState("");
  const [teamB, setTeamB] = useState("");
  const [overs, setOvers] = useState("20");
  const [venue, setVenue] = useState("");
  const card = dark ? "bg-[#0d1929] border-[#1e3a5f]" : "bg-white border-slate-200";
  const inp = `w-full px-4 py-3 rounded-xl border ${dark ? "bg-[#111c2d] border-[#1e3a5f] text-white placeholder-slate-500" : "bg-slate-50 border-slate-300 text-slate-900"} text-base font-semibold focus:outline-none focus:border-orange-500`;

  const proceed = () => {
    if (!teamA.trim() || !teamB.trim()) { alert("Enter both team names."); return; }
    const m = {
      teamA: teamA.trim(), teamB: teamB.trim(),
      overs: parseInt(overs) || 20, venue: venue.trim(), date: nowDate(),
      state: "toss", playersA: [], playersB: [], innings1: null, innings2: null,
    };
    setMatch(m);
    setScreen(SCREENS.TEAMS);
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-10">
      <div className={`w-full max-w-md rounded-2xl border p-6 shadow-2xl ${card}`}>
        <button onClick={() => setScreen(SCREENS.HOME)} className="text-orange-400 text-sm mb-4 flex items-center gap-1">← Back</button>
        <h2 className="text-2xl font-black mb-6">⚙️ Match Setup</h2>
        <div className="space-y-4">
          <div>
            <label className={`text-xs font-bold mb-1 block ${dark ? "text-slate-400" : "text-slate-500"}`}>TEAM A NAME</label>
            <input className={inp} placeholder="e.g. Mumbai Warriors" value={teamA} onChange={e => setTeamA(e.target.value)} />
          </div>
          <div>
            <label className={`text-xs font-bold mb-1 block ${dark ? "text-slate-400" : "text-slate-500"}`}>TEAM B NAME</label>
            <input className={inp} placeholder="e.g. Delhi Strikers" value={teamB} onChange={e => setTeamB(e.target.value)} />
          </div>
          <div>
            <label className={`text-xs font-bold mb-1 block ${dark ? "text-slate-400" : "text-slate-500"}`}>OVERS PER INNINGS</label>
            <div className="grid grid-cols-4 gap-2">
              {["5", "10", "20", "50"].map(o => (
                <button key={o} onClick={() => setOvers(o)} className={`py-3 rounded-xl font-bold transition-all ${overs === o ? "bg-orange-500 text-black" : dark ? "bg-[#111c2d] border border-[#1e3a5f] text-slate-300" : "bg-slate-100 border border-slate-300 text-slate-700"}`}>
                  T{o}
                </button>
              ))}
            </div>
            <input className={`${inp} mt-2`} type="number" placeholder="Custom overs" value={overs} onChange={e => setOvers(e.target.value)} />
          </div>
          <div>
            <label className={`text-xs font-bold mb-1 block ${dark ? "text-slate-400" : "text-slate-500"}`}>VENUE (OPTIONAL)</label>
            <input className={inp} placeholder="e.g. Wankhede Stadium" value={venue} onChange={e => setVenue(e.target.value)} />
          </div>
        </div>
        <button onClick={proceed} className="w-full mt-6 py-4 bg-orange-500 hover:bg-orange-400 text-black font-black text-lg rounded-2xl transition-all active:scale-95">
          Next: Add Players →
        </button>
      </div>
    </div>
  );
}

// ─── TeamsScreen ─────────────────────────────────────────────────────────────
function TeamsScreen({ dark, match, setMatch, setScreen }) {
  const [newPlayerA, setNewPlayerA] = useState("");
  const [newPlayerB, setNewPlayerB] = useState("");
  const [playersA, setPlayersA] = useState(match?.playersA || []);
  const [playersB, setPlayersB] = useState(match?.playersB || []);

  const card = dark ? "bg-[#0d1929] border-[#1e3a5f]" : "bg-white border-slate-200";
  const inp = `flex-1 px-4 py-3 rounded-xl border ${dark ? "bg-[#111c2d] border-[#1e3a5f] text-white placeholder-slate-500" : "bg-slate-50 border-slate-300 text-slate-900"} text-base focus:outline-none focus:border-orange-500`;

  const addA = () => { if (newPlayerA.trim() && playersA.length < 11) { setPlayersA(p => [...p, newPlayerA.trim()]); setNewPlayerA(""); } };
  const addB = () => { if (newPlayerB.trim() && playersB.length < 11) { setPlayersB(p => [...p, newPlayerB.trim()]); setNewPlayerB(""); } };

  const proceed = () => {
    if (playersA.length < 2 || playersB.length < 2) { alert("Add at least 2 players per team."); return; }
    const updated = { ...match, playersA, playersB };
    setMatch(updated);
    setScreen(SCREENS.TOSS);
  };

  const TeamSection = ({ label, players, setPlayers, newVal, setNew, onAdd, color }) => (
    <div className={`rounded-2xl border p-4 ${card}`}>
      <h3 className={`font-black text-lg mb-3 ${color}`}>{label} <span className={`text-sm ${dark ? "text-slate-400" : "text-slate-500"}`}>({players.length}/11)</span></h3>
      <div className="flex gap-2 mb-3">
        <input className={inp} placeholder="Player name" value={newVal} onChange={e => setNew(e.target.value)} onKeyDown={e => e.key === "Enter" && onAdd()} />
        <button onClick={onAdd} className={`px-4 py-3 rounded-xl font-bold bg-orange-500 text-black`}>+</button>
      </div>
      <div className="space-y-2 max-h-48 overflow-y-auto">
        {players.map((p, i) => (
          <div key={i} className={`flex justify-between items-center px-3 py-2 rounded-xl ${dark ? "bg-[#111c2d]" : "bg-slate-50"}`}>
            <span className="text-sm font-semibold">{i + 1}. {p}</span>
            <button onClick={() => setPlayers(pl => pl.filter((_, j) => j !== i))} className="text-red-400 text-xs hover:text-red-300">✕</button>
          </div>
        ))}
      </div>
    </div>
  );

  return (
    <div className="min-h-screen px-4 py-8">
      <div className="w-full max-w-md mx-auto">
        <button onClick={() => setScreen(SCREENS.SETUP)} className="text-orange-400 text-sm mb-4 flex items-center gap-1">← Back</button>
        <h2 className="text-2xl font-black mb-6">👥 Add Players</h2>
        <div className="space-y-4">
          <TeamSection label={match.teamA} players={playersA} setPlayers={setPlayersA} newVal={newPlayerA} setNew={setNewPlayerA} onAdd={addA} color="text-orange-400" />
          <TeamSection label={match.teamB} players={playersB} setPlayers={setPlayersB} newVal={newPlayerB} setNew={setNewPlayerB} onAdd={addB} color="text-cyan-400" />
        </div>
        <button onClick={proceed} className="w-full mt-6 py-4 bg-orange-500 hover:bg-orange-400 text-black font-black text-lg rounded-2xl transition-all active:scale-95">
          Next: Toss →
        </button>
      </div>
    </div>
  );
}

// ─── TossScreen ───────────────────────────────────────────────────────────────
function TossScreen({ dark, match, setMatch, setScreen }) {
  const [tossWinner, setTossWinner] = useState(null);
  const [choice, setChoice] = useState(null);
  const card = dark ? "bg-[#0d1929] border-[#1e3a5f]" : "bg-white border-slate-200";

  const startMatch = () => {
    if (!tossWinner || !choice) { alert("Complete toss details."); return; }
    const batting1st = choice === "bat" ? tossWinner : (tossWinner === match.teamA ? match.teamB : match.teamA);
    const bowling1st = batting1st === match.teamA ? match.teamB : match.teamA;
    const tossStr = `${tossWinner} won toss, elected to ${choice}`;
    const batters = batting1st === match.teamA ? match.playersA : match.playersB;
    const bowlers2 = bowling1st === match.teamA ? match.playersA : match.playersB;
    const initBatsmen = batters.map(n => ({ name: n, runs: 0, balls: 0, fours: 0, sixes: 0, out: false, howOut: null }));
    const initBowlers = bowlers2.map(n => ({ name: n, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0 }));
    const innings1 = {
      battingTeam: batting1st, bowlingTeam: bowling1st,
      runs: 0, wickets: 0, balls: 0, extras: { wides: 0, noballs: 0, byes: 0, total: 0 },
      batsmen: initBatsmen, bowlers: initBowlers,
      currentBat1: 0, currentBat2: 1, currentBowler: 0,
      ballLog: [], completed: false,
    };
    const updated = { ...match, toss: tossStr, innings1, state: "innings1" };
    setMatch(updated);
    setScreen(SCREENS.SCORING);
  };

  const Btn = ({ label, val, active, setActive }) => (
    <button onClick={() => setActive(val)} className={`flex-1 py-3 rounded-xl font-bold transition-all text-sm ${active === val ? "bg-orange-500 text-black" : dark ? "bg-[#111c2d] border border-[#1e3a5f] text-slate-300" : "bg-slate-100 border border-slate-300 text-slate-700"}`}>{label}</button>
  );

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4">
      <div className={`w-full max-w-md rounded-2xl border p-6 shadow-2xl ${card}`}>
        <button onClick={() => setScreen(SCREENS.TEAMS)} className="text-orange-400 text-sm mb-4">← Back</button>
        <div className="text-center mb-6">
          <div className="text-5xl mb-2">🪙</div>
          <h2 className="text-2xl font-black">Toss</h2>
        </div>
        <div className="space-y-5">
          <div>
            <label className={`text-xs font-bold mb-2 block ${dark ? "text-slate-400" : "text-slate-500"}`}>WHO WON THE TOSS?</label>
            <div className="flex gap-2">
              <Btn label={match.teamA} val={match.teamA} active={tossWinner} setActive={setTossWinner} />
              <Btn label={match.teamB} val={match.teamB} active={tossWinner} setActive={setTossWinner} />
            </div>
          </div>
          {tossWinner && (
            <div>
              <label className={`text-xs font-bold mb-2 block ${dark ? "text-slate-400" : "text-slate-500"}`}>ELECTED TO?</label>
              <div className="flex gap-2">
                <Btn label="🏏 Bat" val="bat" active={choice} setActive={setChoice} />
                <Btn label="🎯 Bowl" val="bowl" active={choice} setActive={setChoice} />
              </div>
            </div>
          )}
        </div>
        {tossWinner && choice && (
          <div className={`mt-4 p-3 rounded-xl text-center text-sm font-semibold ${dark ? "bg-[#0a1628]" : "bg-orange-50"}`}>
            <span className="text-orange-400">{choice === "bat" ? tossWinner : (tossWinner === match.teamA ? match.teamB : match.teamA)}</span> will bat first
          </div>
        )}
        <button onClick={startMatch} className="w-full mt-6 py-4 bg-orange-500 hover:bg-orange-400 text-black font-black text-lg rounded-2xl transition-all active:scale-95">
          🏏 Start Match
        </button>
      </div>
    </div>
  );
}

// ─── ScoringScreen ────────────────────────────────────────────────────────────
function ScoringScreen({ dark, match, setMatch, setScreen, finishMatch, showToast }) {
  const [showLog, setShowLog] = useState(false);
  const [showChangeBowler, setShowChangeBowler] = useState(false);
  const [showChangeBat, setShowChangeBat] = useState(false);
  const [newBatsman, setNewBatsman] = useState(null);
  const [nextBowlerIdx, setNextBowlerIdx] = useState(null);
  const [wicketModal, setWicketModal] = useState(false);
  const [wicketType, setWicketType] = useState("caught");

  const innings = match.state === "innings1" ? match.innings1 : match.innings2;
  if (!innings) return null;

  const { runs, wickets, balls, extras, batsmen, bowlers, currentBat1, currentBat2, currentBowler, ballLog } = innings;
  const bat1 = batsmen[currentBat1];
  const bat2 = batsmen[currentBat2];
  const bowler = bowlers[currentBowler];
  const maxBalls = match.overs * 6;
  const isInn1 = match.state === "innings1";
  const target = isInn1 ? null : (match.innings1.runs + 1);
  const runRate = rr(runs, balls);
  const reqRate = !isInn1 && balls < maxBalls ? rr((target - runs), maxBalls - balls) : null;

  const updateInnings = (patch) => {
    const inn = match.state === "innings1" ? "innings1" : "innings2";
    const updated = { ...match, [inn]: { ...(match[inn]), ...patch } };
    setMatch(updated);
    return updated;
  };

  const endOfOver = (updated) => {
    const inn = updated.state === "innings1" ? updated.innings1 : updated.innings2;
    if (inn.balls % 6 === 0 && inn.balls > 0) {
      setShowChangeBowler(true);
    }
  };

  const score = (type, val = 0) => {
    let inn = { ...innings };
    let newBalls = inn.balls;
    let newRuns = inn.runs;
    let newExtras = { ...inn.extras };
    let newBatsmen = inn.batsmen.map(b => ({ ...b }));
    let newBowlers = inn.bowlers.map(b => ({ ...b }));
    let logEntry = "";

    if (type === "wicket") {
      setWicketModal(true); return;
    }

    if (type === "wide") {
      newRuns += 1; newExtras.wides += 1; newExtras.total += 1;
      newBowlers[currentBowler].runs += 1;
      logEntry = "Wd";
    } else if (type === "noball") {
      newRuns += 1; newExtras.noballs += 1; newExtras.total += 1;
      newBowlers[currentBowler].runs += 1;
      logEntry = "Nb";
    } else {
      newBalls += 1;
      newRuns += val;
      newBatsmen[currentBat1].runs += val;
      newBatsmen[currentBat1].balls += 1;
      if (val === 4) newBatsmen[currentBat1].fours += 1;
      if (val === 6) newBatsmen[currentBat1].sixes += 1;
      newBowlers[currentBowler].runs += val;
      newBowlers[currentBowler].balls += 1;
      logEntry = val === 0 ? "•" : String(val);

      // Rotate strike on odd runs
      let cb1 = currentBat1, cb2 = currentBat2;
      if (val % 2 !== 0) { cb1 = currentBat2; cb2 = currentBat1; }
      // End of over: rotate strike
      if (newBalls % 6 === 0) { cb1 = currentBat2; cb2 = currentBat1; }
      inn = { ...inn, currentBat1: cb1, currentBat2: cb2 };
    }

    const newLog = [...(inn.ballLog || []), logEntry];
    const patch = { runs: newRuns, balls: newBalls, extras: newExtras, batsmen: newBatsmen, bowlers: newBowlers, ballLog: newLog, currentBat1: inn.currentBat1, currentBat2: inn.currentBat2 };

    // Check win/end conditions
    const allOut = newBatsmen.filter(b => !b.out).length < 2;
    const oversUp = newBalls >= maxBalls;
    const chaseComplete = !isInn1 && newRuns >= target;

    if (chaseComplete || allOut || oversUp) {
      const finalPatch = { ...patch, completed: true };
      const updated = updateInnings(finalPatch);
      if (isInn1) {
        setScreen(SCREENS.INNINGS_BREAK);
      } else {
        finishMatch(updated);
      }
      return;
    }

    const updated = updateInnings(patch);
    endOfOver(updated);
  };

  const applyWicket = () => {
    let inn = { ...innings };
    let newBatsmen = inn.batsmen.map(b => ({ ...b }));
    let newBowlers = inn.bowlers.map(b => ({ ...b }));
    const newBalls = inn.balls + 1;
    newBatsmen[currentBat1].out = true;
    newBatsmen[currentBat1].howOut = wicketType;
    newBatsmen[currentBat1].balls += 1;
    newBowlers[currentBowler].wickets += 1;
    newBowlers[currentBowler].balls += 1;
    const newWickets = inn.wickets + 1;
    const newLog = [...(inn.ballLog || []), "W"];

    const allOut = newBatsmen.filter(b => !b.out).length < 2;
    const oversUp = newBalls >= maxBalls;

    if (allOut || oversUp) {
      const patch = { wickets: newWickets, balls: newBalls, batsmen: newBatsmen, bowlers: newBowlers, ballLog: newLog, completed: true };
      const updated = updateInnings(patch);
      setWicketModal(false);
      if (isInn1) setScreen(SCREENS.INNINGS_BREAK);
      else finishMatch(updated);
      return;
    }

    // Find next batsman
    const nextIn = newBatsmen.findIndex((b, i) => !b.out && i !== currentBat1 && i !== currentBat2);
    if (nextIn === -1) {
      showToast("All out!", "error");
      setWicketModal(false);
      return;
    }
    setWicketModal(false);
    setNewBatsman(nextIn);
    setShowChangeBat(true);
    const patch = { wickets: newWickets, balls: newBalls, batsmen: newBatsmen, bowlers: newBowlers, ballLog: newLog };
    updateInnings(patch);
    // end of over check
    if (newBalls % 6 === 0) setShowChangeBowler(true);
  };

  const card = dark ? "bg-[#0d1929] border-[#1e3a5f]" : "bg-white border-slate-200";
  const BtnScore = ({ label, val, color, type }) => (
    <button onClick={() => score(type || "run", val)} className={`py-5 rounded-2xl font-black text-2xl transition-all active:scale-90 shadow-lg ${color}`} style={{ touchAction: "manipulation" }}>
      {label}
    </button>
  );

  // Ball log grouped by overs
  const overs = [];
  for (let i = 0; i < ballLog.length; i += 6) { overs.push(ballLog.slice(i, i + 6)); }

  return (
    <div className="min-h-screen px-3 py-4 max-w-md mx-auto">
      {/* Header */}
      <div className={`rounded-2xl border p-4 mb-3 ${card}`}>
        <div className="flex justify-between items-center mb-1">
          <span className="font-black text-lg text-orange-400">{innings.battingTeam}</span>
          <span className={`text-xs px-2 py-1 rounded-full ${dark ? "bg-[#111c2d] text-slate-400" : "bg-slate-100 text-slate-500"}`}>{isInn1 ? "1st Innings" : "2nd Innings"}</span>
        </div>
        <div className="flex items-baseline gap-3">
          <span className="text-5xl font-black">{runs}/{wickets}</span>
          <span className={`text-xl font-bold ${dark ? "text-slate-400" : "text-slate-500"}`}>({overStr(balls)})</span>
        </div>
        <div className="flex gap-4 mt-2 text-sm">
          <span className={dark ? "text-slate-400" : "text-slate-500"}>RR: <span className="text-cyan-400 font-bold">{runRate}</span></span>
          {reqRate && <span className={dark ? "text-slate-400" : "text-slate-500"}>REQ: <span className="text-red-400 font-bold">{reqRate}</span></span>}
          {target && <span className={dark ? "text-slate-400" : "text-slate-500"}>Target: <span className="text-yellow-400 font-bold">{target}</span></span>}
          <span className={dark ? "text-slate-400" : "text-slate-500"}>Ov left: <span className="font-bold">{match.overs - Math.floor(balls / 6)}.{6 - (balls % 6) === 6 ? 0 : 6 - (balls % 6)}</span></span>
        </div>
      </div>

      {/* Batsmen */}
      <div className={`rounded-2xl border p-3 mb-3 ${card}`}>
        <div className="grid grid-cols-2 gap-2">
          {[{ b: bat1, idx: currentBat1, strike: true }, { b: bat2, idx: currentBat2, strike: false }].map(({ b, strike }) => (
            <div key={b.name} className={`p-2 rounded-xl ${strike ? dark ? "bg-orange-500/10 border border-orange-500/30" : "bg-orange-50 border border-orange-200" : dark ? "bg-[#111c2d]" : "bg-slate-50"}`}>
              <div className="flex items-center gap-1">
                {strike && <span className="text-orange-400 text-xs">🏏</span>}
                <span className="text-xs font-bold truncate">{b.name}</span>
              </div>
              <div className="font-black text-lg">{b.runs} <span className="text-xs font-normal text-slate-400">({b.balls})</span></div>
              <div className="text-xs text-slate-400">4s:{b.fours} 6s:{b.sixes} SR:{b.balls > 0 ? ((b.runs / b.balls) * 100).toFixed(0) : 0}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Bowler */}
      <div className={`rounded-2xl border p-3 mb-3 flex justify-between items-center ${card}`}>
        <div>
          <div className="text-xs font-bold text-cyan-400">🎯 {bowler.name}</div>
          <div className="text-sm font-bold">{overStr(bowler.balls)}-{bowler.runs}-{bowler.wickets}w</div>
        </div>
        <button onClick={() => setShowChangeBowler(true)} className={`text-xs px-3 py-1.5 rounded-lg border ${dark ? "border-[#1e3a5f] text-slate-300" : "border-slate-300 text-slate-600"}`}>Change</button>
      </div>

      {/* Score Buttons */}
      <div className="grid grid-cols-4 gap-2 mb-3">
        <BtnScore label="0" val={0} color={`${dark ? "bg-[#0d1929] border border-[#1e3a5f] text-white" : "bg-white border border-slate-300 text-slate-800"}`} />
        <BtnScore label="1" val={1} color={`${dark ? "bg-[#0d1929] border border-[#1e3a5f] text-white" : "bg-white border border-slate-300 text-slate-800"}`} />
        <BtnScore label="2" val={2} color={`${dark ? "bg-[#0d1929] border border-[#1e3a5f] text-white" : "bg-white border border-slate-300 text-slate-800"}`} />
        <BtnScore label="3" val={3} color={`${dark ? "bg-[#0d1929] border border-[#1e3a5f] text-white" : "bg-white border border-slate-300 text-slate-800"}`} />
      </div>
      <div className="grid grid-cols-3 gap-2 mb-3">
        <BtnScore label="4️⃣" val={4} color="bg-emerald-600 hover:bg-emerald-500 text-white shadow-emerald-500/30" />
        <BtnScore label="6️⃣" val={6} color="bg-blue-600 hover:bg-blue-500 text-white shadow-blue-500/30" />
        <button onClick={() => score("wicket")} className="py-5 rounded-2xl font-black text-2xl bg-red-600 hover:bg-red-500 text-white shadow-lg shadow-red-500/30 transition-all active:scale-90">🏏W</button>
      </div>
      <div className="grid grid-cols-2 gap-2 mb-3">
        <button onClick={() => score("wide")} className={`py-4 rounded-2xl font-bold text-base border ${dark ? "border-yellow-500/50 text-yellow-400 bg-yellow-500/10" : "border-yellow-400 text-yellow-600 bg-yellow-50"} active:scale-95`}>Wide</button>
        <button onClick={() => score("noball")} className={`py-4 rounded-2xl font-bold text-base border ${dark ? "border-purple-500/50 text-purple-400 bg-purple-500/10" : "border-purple-400 text-purple-600 bg-purple-50"} active:scale-95`}>No Ball</button>
      </div>

      {/* Ball Log */}
      <div className={`rounded-2xl border p-3 mb-3 ${card}`}>
        <div className="flex justify-between items-center mb-2">
          <span className="text-xs font-bold text-slate-400">BALL LOG</span>
          <button onClick={() => setShowLog(s => !s)} className="text-xs text-orange-400">{showLog ? "Hide" : "Show all"}</button>
        </div>
        <div className="flex flex-wrap gap-1">
          {(showLog ? overs : overs.slice(-3)).map((ov, oi) => (
            <div key={oi} className="flex items-center gap-1">
              <span className="text-xs text-slate-500 w-5">{showLog ? oi + 1 : overs.length - 3 + oi + 1}.</span>
              {ov.map((b, bi) => (
                <span key={bi} className={`w-7 h-7 flex items-center justify-center rounded-full text-xs font-bold ${b === "W" ? "bg-red-600 text-white" : b === "Wd" ? "bg-yellow-500 text-black" : b === "Nb" ? "bg-purple-500 text-white" : b === "4" ? "bg-emerald-600 text-white" : b === "6" ? "bg-blue-600 text-white" : dark ? "bg-[#1e3a5f] text-white" : "bg-slate-200 text-slate-800"}`}>{b}</span>
              ))}
            </div>
          ))}
        </div>
      </div>

      {/* End Match */}
      <button onClick={() => { if (window.confirm("End match now?")) { const inn = match.state === "innings1" ? "innings1" : "innings2"; const updated = { ...match, [inn]: { ...innings, completed: true } }; if (match.state === "innings1") setScreen(SCREENS.INNINGS_BREAK); else finishMatch(updated); }}} className={`w-full py-3 rounded-2xl font-bold border text-sm ${dark ? "border-red-500/30 text-red-400" : "border-red-300 text-red-600"}`}>
        End Innings
      </button>

      {/* Wicket Modal */}
      {wicketModal && (
        <div className="fixed inset-0 bg-black/70 flex items-end justify-center z-50 px-4 pb-8">
          <div className={`w-full max-w-md rounded-2xl border p-5 ${card}`}>
            <h3 className="text-xl font-black mb-4 text-red-400">🏏 Wicket</h3>
            <div className="grid grid-cols-2 gap-2 mb-4">
              {["caught", "bowled", "lbw", "run out", "stumped", "hit wicket"].map(t => (
                <button key={t} onClick={() => setWicketType(t)} className={`py-3 rounded-xl font-bold text-sm capitalize ${wicketType === t ? "bg-red-600 text-white" : dark ? "bg-[#111c2d] border border-[#1e3a5f] text-slate-300" : "bg-slate-100 border border-slate-300 text-slate-700"}`}>{t}</button>
              ))}
            </div>
            <div className="flex gap-2">
              <button onClick={() => setWicketModal(false)} className={`flex-1 py-3 rounded-xl border font-bold ${dark ? "border-[#1e3a5f] text-slate-300" : "border-slate-300 text-slate-700"}`}>Cancel</button>
              <button onClick={applyWicket} className="flex-1 py-3 rounded-xl bg-red-600 text-white font-bold">Confirm W</button>
            </div>
          </div>
        </div>
      )}

      {/* Change Bowler Modal */}
      {showChangeBowler && (
        <div className="fixed inset-0 bg-black/70 flex items-end justify-center z-50 px-4 pb-8">
          <div className={`w-full max-w-md rounded-2xl border p-5 ${card}`}>
            <h3 className="text-xl font-black mb-4 text-cyan-400">🎯 Select Bowler</h3>
            <div className="space-y-2 max-h-72 overflow-y-auto">
              {innings.bowlers.map((b, i) => (
                <button key={i} onClick={() => { setNextBowlerIdx(i); }} disabled={i === currentBowler} className={`w-full py-3 px-4 rounded-xl font-semibold text-left flex justify-between items-center ${nextBowlerIdx === i ? "bg-cyan-500 text-black" : i === currentBowler ? "opacity-40 cursor-not-allowed " + (dark ? "bg-[#111c2d]" : "bg-slate-100") : dark ? "bg-[#111c2d] border border-[#1e3a5f] text-slate-200" : "bg-slate-50 border border-slate-300 text-slate-800"}`}>
                  <span>{b.name}</span>
                  <span className="text-xs opacity-60">{overStr(b.balls)}-{b.runs}-{b.wickets}w</span>
                </button>
              ))}
            </div>
            <button onClick={() => {
              if (nextBowlerIdx === null) { alert("Select a bowler."); return; }
              updateInnings({ currentBowler: nextBowlerIdx });
              setNextBowlerIdx(null);
              setShowChangeBowler(false);
            }} className="w-full mt-3 py-3 bg-cyan-500 text-black font-black rounded-xl">Confirm Bowler</button>
          </div>
        </div>
      )}

      {/* Change Batsman Modal */}
      {showChangeBat && (
        <div className="fixed inset-0 bg-black/70 flex items-end justify-center z-50 px-4 pb-8">
          <div className={`w-full max-w-md rounded-2xl border p-5 ${card}`}>
            <h3 className="text-xl font-black mb-4 text-orange-400">🏏 New Batsman</h3>
            <div className="space-y-2 max-h-64 overflow-y-auto">
              {innings.batsmen.map((b, i) => (
                !b.out && i !== currentBat2 && i !== currentBat1 && (
                  <button key={i} onClick={() => setNewBatsman(i)} className={`w-full py-3 px-4 rounded-xl font-semibold text-left ${newBatsman === i ? "bg-orange-500 text-black" : dark ? "bg-[#111c2d] border border-[#1e3a5f] text-slate-200" : "bg-slate-50 border border-slate-300 text-slate-800"}`}>
                    {b.name}
                  </button>
                )
              ))}
            </div>
            <button onClick={() => {
              if (newBatsman === null) { alert("Select new batsman."); return; }
              updateInnings({ currentBat1: newBatsman });
              setNewBatsman(null);
              setShowChangeBat(false);
            }} className="w-full mt-3 py-3 bg-orange-500 text-black font-black rounded-xl">Send In</button>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── InningsBreak ─────────────────────────────────────────────────────────────
function InningsBreak({ dark, match, setMatch, setScreen, showToast }) {
  const inn1 = match.innings1;
  const target = inn1.runs + 1;
  const card = dark ? "bg-[#0d1929] border-[#1e3a5f]" : "bg-white border-slate-200";
  const inp = `w-full px-4 py-3 rounded-xl border ${dark ? "bg-[#111c2d] border-[#1e3a5f] text-white placeholder-slate-500" : "bg-slate-50 border-slate-300 text-slate-900"} text-base focus:outline-none focus:border-orange-500`;
  const [bowlerPicked, setBowlerPicked] = useState(0);
  const [bat1Picked, setBat1Picked] = useState(0);
  const [bat2Picked, setBat2Picked] = useState(1);

  const startInn2 = () => {
    const batting2 = match.teamB === inn1.battingTeam ? match.teamA : match.teamB;
    const bowling2 = batting2 === match.teamA ? match.teamB : match.teamA;
    const batters2 = batting2 === match.teamA ? match.playersA : match.playersB;
    const bowlers2 = bowling2 === match.teamA ? match.playersA : match.playersB;
    const innings2 = {
      battingTeam: batting2, bowlingTeam: bowling2,
      runs: 0, wickets: 0, balls: 0,
      extras: { wides: 0, noballs: 0, byes: 0, total: 0 },
      batsmen: batters2.map(n => ({ name: n, runs: 0, balls: 0, fours: 0, sixes: 0, out: false, howOut: null })),
      bowlers: bowlers2.map(n => ({ name: n, overs: 0, balls: 0, runs: 0, wickets: 0, maidens: 0 })),
      currentBat1: bat1Picked, currentBat2: bat2Picked, currentBowler: bowlerPicked,
      ballLog: [], completed: false,
    };
    const updated = { ...match, innings2, state: "innings2" };
    setMatch(updated);
    setScreen(SCREENS.SCORING);
  };

  const batting2 = match.teamB === inn1.battingTeam ? match.teamA : match.teamB;
  const bowling2 = batting2 === match.teamA ? match.teamB : match.teamA;
  const batters2 = batting2 === match.teamA ? match.playersA : match.playersB;
  const bowlers2 = bowling2 === match.teamA ? match.playersA : match.playersB;

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-8">
      <div className={`w-full max-w-md rounded-2xl border p-6 shadow-2xl ${card}`}>
        <div className="text-center mb-6">
          <div className="text-5xl mb-2">⏸️</div>
          <h2 className="text-2xl font-black">Innings Break</h2>
        </div>
        <div className={`rounded-xl p-4 mb-6 ${dark ? "bg-[#0a1628]" : "bg-slate-50"}`}>
          <div className="text-center">
            <div className="text-3xl font-black text-orange-400">{inn1.battingTeam}</div>
            <div className="text-4xl font-black my-1">{inn1.runs}/{inn1.wickets}</div>
            <div className={`text-sm ${dark ? "text-slate-400" : "text-slate-500"}`}>{overStr(inn1.balls)} overs</div>
          </div>
          <div className="mt-3 p-3 bg-orange-500 rounded-xl text-center">
            <span className="font-black text-black text-lg">{batting2} needs {target} to win</span>
          </div>
        </div>
        <h3 className="font-bold text-sm mb-3 text-slate-400">SETUP 2ND INNINGS</h3>
        <div className="space-y-3">
          <div>
            <label className="text-xs text-slate-400 font-bold mb-1 block">OPENING BATSMAN 1</label>
            <select className={inp} value={bat1Picked} onChange={e => setBat1Picked(+e.target.value)}>
              {batters2.map((p, i) => <option key={i} value={i}>{p}</option>)}
            </select>
          </div>
          <div>
            <label className="text-xs text-slate-400 font-bold mb-1 block">OPENING BATSMAN 2</label>
            <select className={inp} value={bat2Picked} onChange={e => setBat2Picked(+e.target.value)}>
              {batters2.map((p, i) => <option key={i} value={i}>{p}</option>)}
            </select>
          </div>
          <div>
            <label className="text-xs text-slate-400 font-bold mb-1 block">OPENING BOWLER</label>
            <select className={inp} value={bowlerPicked} onChange={e => setBowlerPicked(+e.target.value)}>
              {bowlers2.map((p, i) => <option key={i} value={i}>{p}</option>)}
            </select>
          </div>
        </div>
        <button onClick={startInn2} className="w-full mt-6 py-4 bg-orange-500 hover:bg-orange-400 text-black font-black text-lg rounded-2xl transition-all active:scale-95">
          🏏 Start 2nd Innings
        </button>
      </div>
    </div>
  );
}

// ─── SummaryScreen ────────────────────────────────────────────────────────────
function SummaryScreen({ dark, match, setScreen, showToast }) {
  const [motm, setMotm] = useState(match.motm || "");
  const [motmSaved, setMotmSaved] = useState(!!match.motm);
  const card = dark ? "bg-[#0d1929] border-[#1e3a5f]" : "bg-white border-slate-200";
  const inp = `flex-1 px-4 py-2 rounded-xl border ${dark ? "bg-[#111c2d] border-[#1e3a5f] text-white placeholder-slate-500" : "bg-slate-50 border-slate-300 text-slate-900"} text-base focus:outline-none focus:border-orange-500`;

  const inn1 = match.innings1;
  const inn2 = match.innings2;

  const winner = (() => {
    if (!inn2 || !inn2.completed) return inn1 ? `${inn1.battingTeam} scored ${inn1.runs}/${inn1.wickets}` : null;
    if (inn2.runs > inn1.runs) {
      const wkts = inn2.batsmen.filter(b => !b.out).length;
      return `🏆 ${inn2.battingTeam} won by ${wkts} wickets`;
    }
    if (inn1.runs > inn2.runs) return `🏆 ${inn1.battingTeam} won by ${inn1.runs - inn2.runs} runs`;
    return "🤝 Match Tied!";
  })();

  const BatCard = ({ inn, team }) => (
    <div className={`rounded-2xl border p-4 mb-3 ${card}`}>
      <h3 className="font-black text-base text-orange-400 mb-2">{team} Batting</h3>
      <div className={`text-xs font-bold mb-1 grid grid-cols-7 gap-1 ${dark ? "text-slate-500" : "text-slate-400"}`}>
        <span className="col-span-2">Player</span><span>R</span><span>B</span><span>4s</span><span>6s</span><span>SR</span>
      </div>
      {(inn.batsmen || []).map((b, i) => (
        <div key={i} className={`grid grid-cols-7 gap-1 py-1.5 text-sm border-t ${dark ? "border-[#1e3a5f]" : "border-slate-100"}`}>
          <span className="col-span-2 font-semibold truncate text-xs">{b.name}{b.out ? <span className="text-red-400 text-xs"> †</span> : <span className="text-green-400 text-xs"> *</span>}</span>
          <span className="font-black">{b.runs}</span>
          <span>{b.balls}</span>
          <span className="text-emerald-400">{b.fours}</span>
          <span className="text-blue-400">{b.sixes}</span>
          <span className="text-xs">{b.balls > 0 ? ((b.runs / b.balls) * 100).toFixed(0) : 0}</span>
        </div>
      ))}
      <div className={`mt-2 pt-2 border-t text-sm ${dark ? "border-[#1e3a5f] text-slate-400" : "border-slate-100 text-slate-500"}`}>
        Extras: {inn.extras?.total || 0} (wd:{inn.extras?.wides||0} nb:{inn.extras?.noballs||0})
      </div>
      <div className="font-black text-xl mt-1 text-orange-400">{inn.runs}/{inn.wickets} <span className="text-sm font-normal text-slate-400">({overStr(inn.balls)} ov)</span></div>
    </div>
  );

  const BowlCard = ({ inn }) => (
    <div className={`rounded-2xl border p-4 mb-3 ${card}`}>
      <h3 className="font-black text-base text-cyan-400 mb-2">{inn.bowlingTeam} Bowling</h3>
      <div className={`text-xs font-bold mb-1 grid grid-cols-5 gap-1 ${dark ? "text-slate-500" : "text-slate-400"}`}>
        <span className="col-span-2">Bowler</span><span>O</span><span>R</span><span>W</span>
      </div>
      {(inn.bowlers || []).filter(b => b.balls > 0).map((b, i) => (
        <div key={i} className={`grid grid-cols-5 gap-1 py-1.5 text-sm border-t ${dark ? "border-[#1e3a5f]" : "border-slate-100"}`}>
          <span className="col-span-2 font-semibold truncate text-xs">{b.name}</span>
          <span>{overStr(b.balls)}</span>
          <span>{b.runs}</span>
          <span className="font-black text-red-400">{b.wickets}</span>
        </div>
      ))}
    </div>
  );

  const shareWA = () => {
    const txt = `🏏 *${match.teamA} vs ${match.teamB}*\n\n1st Inn: ${inn1?.battingTeam} ${inn1?.runs}/${inn1?.wickets} (${overStr(inn1?.balls||0)} ov)\n${inn2 ? `2nd Inn: ${inn2.battingTeam} ${inn2.runs}/${inn2.wickets} (${overStr(inn2.balls||0)} ov)\n` : ""}\n${winner || ""}\n\nScored with CricScore App`;
    window.open(`https://wa.me/?text=${encodeURIComponent(txt)}`);
  };

  return (
    <div className="min-h-screen px-3 py-6 max-w-md mx-auto">
      {/* Result */}
      <div className={`rounded-2xl border p-5 mb-4 text-center ${card}`}>
        <div className="text-4xl mb-2">🏆</div>
        <h2 className="text-xl font-black text-orange-400">{match.teamA} vs {match.teamB}</h2>
        <p className={`text-sm mb-2 ${dark ? "text-slate-400" : "text-slate-500"}`}>{match.date} • {match.venue || "Local Ground"}</p>
        <div className="text-lg font-black text-emerald-400">{winner}</div>
        {match.toss && <p className={`text-xs mt-1 ${dark ? "text-slate-500" : "text-slate-400"}`}>{match.toss}</p>}
      </div>

      {/* MOTM */}
      <div className={`rounded-2xl border p-4 mb-4 ${card}`}>
        <label className="text-xs font-bold text-yellow-400 mb-2 block">🏅 MAN OF THE MATCH</label>
        <div className="flex gap-2">
          <input className={inp} placeholder="Player name" value={motm} onChange={e => setMotm(e.target.value)} disabled={motmSaved} />
          {!motmSaved
            ? <button onClick={() => { setMotmSaved(true); const d = load(); if (d.history) { const idx = d.history.findIndex(h => h.date === match.date && h.teamA === match.teamA); if (idx !== -1) d.history[idx].motm = motm; save(d); } showToast("MOTM saved!"); }} className="px-4 py-2 bg-yellow-500 text-black font-bold rounded-xl">Save</button>
            : <button onClick={() => setMotmSaved(false)} className={`px-4 py-2 rounded-xl border font-bold text-xs ${dark ? "border-[#1e3a5f] text-slate-300" : "border-slate-300 text-slate-600"}`}>Edit</button>
          }
        </div>
      </div>

      {/* Scorecards */}
      {inn1 && <><BatCard inn={inn1} team={inn1.battingTeam} /><BowlCard inn={inn1} /></>}
      {inn2 && <><BatCard inn={inn2} team={inn2.battingTeam} /><BowlCard inn={inn2} /></>}

      {/* Actions */}
      <div className="space-y-2 mt-4">
        <button onClick={() => generatePDF({ ...match, motm })} className="w-full py-4 bg-orange-500 hover:bg-orange-400 text-black font-black text-lg rounded-2xl active:scale-95 shadow-lg">
          📄 Download PDF Scorecard
        </button>
        <button onClick={shareWA} className="w-full py-4 bg-green-600 hover:bg-green-500 text-white font-black text-lg rounded-2xl active:scale-95">
          💬 Share on WhatsApp
        </button>
        <button onClick={() => setScreen(SCREENS.HOME)} className={`w-full py-4 rounded-2xl font-bold border text-base ${dark ? "border-[#1e3a5f] text-slate-300" : "border-slate-300 text-slate-700"}`}>
          🏠 Home
        </button>
      </div>
    </div>
  );
}

// ─── HistoryScreen ────────────────────────────────────────────────────────────
function HistoryScreen({ dark, history, setScreen, setMatch }) {
  const card = dark ? "bg-[#0d1929] border-[#1e3a5f]" : "bg-white border-slate-200";
  return (
    <div className="min-h-screen px-4 py-8 max-w-md mx-auto">
      <button onClick={() => setScreen(SCREENS.HOME)} className="text-orange-400 text-sm mb-4 flex items-center gap-1">← Back</button>
      <h2 className="text-2xl font-black mb-6">📋 Match History</h2>
      {history.length === 0 ? (
        <div className="text-center mt-20 text-slate-400">No matches yet. Start scoring!</div>
      ) : (
        <div className="space-y-3">
          {history.map((m, i) => {
            const inn1 = m.innings1;
            const inn2 = m.innings2;
            const winner = inn2?.completed ? (inn2.runs > inn1.runs ? inn2.battingTeam : inn1.runs > inn2.runs ? inn1.battingTeam : "Tie") : null;
            return (
              <div key={i} onClick={() => { setMatch(m); setScreen(SCREENS.SUMMARY); }} className={`p-4 rounded-2xl border cursor-pointer ${card} hover:border-orange-500 transition-all`}>
                <div className="flex justify-between items-start">
                  <div>
                    <div className="font-black">{m.teamA} vs {m.teamB}</div>
                    <div className={`text-xs mt-1 ${dark ? "text-slate-400" : "text-slate-500"}`}>{m.date} • {m.venue || "Local Ground"}</div>
                  </div>
                  {winner && <span className="text-xs bg-orange-500 text-black px-2 py-1 rounded-full font-bold">{winner}</span>}
                </div>
                <div className="mt-2 flex gap-4 text-sm text-orange-400">
                  {inn1 && <span>{inn1.battingTeam} {inn1.runs}/{inn1.wickets}</span>}
                  {inn2 && <span>| {inn2.battingTeam} {inn2.runs}/{inn2.wickets}</span>}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
